server:
    port: 3010

spring:
    application:
        name: user
    datasource:
        url: jdbc:postgresql://localhost:5433/streaming_users?createDatabaseIfNotExist=true
        username: postgres
        password: postgres123
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
    rabbitmq:
        host: localhost
        port: 5672
        username: admin
        password: admin
    jwt:
        secret: secret